import {NgModule} from '@angular/core';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatInputModule,
  MatCardModule,
  MatSelectModule,
  MatProgressSpinnerModule,
  MatIconModule,
  MatSidenavModule,
  MatListModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatDialogModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatExpansionModule,
  MatRadioModule,
  MatTabsModule,
  MatTreeModule,
  MatDatepickerModule,
  MatStepperModule,
  MatBadgeModule
} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatExpansionModule,
    MatRadioModule,
    MatTabsModule,
    MatTreeModule,
    MatDatepickerModule,
    MatStepperModule,
    MatBadgeModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatExpansionModule,
    MatRadioModule,
    MatTabsModule,
    MatTreeModule,
    MatDatepickerModule,
    MatStepperModule,
    MatBadgeModule
  ]
})

export class MaterialModule {}
